repos:
  # configure shared hooks that you want to run on all repositories here
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/google/yapf
    rev: v0.31.0
    hooks:
      - id: yapf
        name: "yapf (for labelbox-python repo)"
        # args: ['--parallel --style "google" ']
