# Triggers a pypi publication when a release is created

name: Publish Python Package

on:
  release:
    types: [created, updated]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build
      run: |
        python setup.py sdist bdist_wheel
        
    - name: Update help docs
      run: |
        python setup.py install
        python ./tools/api_reference_generator.py ${{ secrets.HELPDOCS_API_KEY }}

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
